# Site settings
title: Teisten
email: johannes.e.jansson@gmail.com
description: >-
  Johannes Jansson. Apologet, predikant, teolog, filosof, ingenjör. Här delar
  jag tankar och undervisningsmaterial. 
baseurl: ""
url: "https://teisten.se"
lang: sv
timezone: Europe/Stockholm

# Misc
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
logo: /assets/img/t_100.png
search: true

gems:
  - jekyll-paginate

paginate: 5
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
